//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAPADDON.MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUFD
    {
        public string TableID { get; set; }
        public short FieldID { get; set; }
        public string AliasID { get; set; }
        public string Descr { get; set; }
        public string TypeID { get; set; }
        public string EditType { get; set; }
        public Nullable<short> SizeID { get; set; }
        public Nullable<short> EditSize { get; set; }
        public string Dflt { get; set; }
        public string NotNull { get; set; }
        public string IndexID { get; set; }
        public string RTable { get; set; }
        public Nullable<short> RField { get; set; }
        public string Action { get; set; }
        public string Sys { get; set; }
        public Nullable<System.DateTime> DfltDate { get; set; }
        public string RelUDO { get; set; }
        public string ValidRule { get; set; }
        public string RelSO { get; set; }
        public string RThrdPTab { get; set; }
        public string RThrdPFld { get; set; }
    }
}
